// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package testpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestMessage struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	City                 *string  `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMessage) Reset()         { *m = TestMessage{} }
func (m *TestMessage) String() string { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()    {}
func (*TestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *TestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMessage.Unmarshal(m, b)
}
func (m *TestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMessage.Marshal(b, m, deterministic)
}
func (m *TestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMessage.Merge(m, src)
}
func (m *TestMessage) XXX_Size() int {
	return xxx_messageInfo_TestMessage.Size(m)
}
func (m *TestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestMessage proto.InternalMessageInfo

func (m *TestMessage) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *TestMessage) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

type TestRequest struct {
	Lower                *string  `protobuf:"bytes,1,req,name=lower" json:"lower,omitempty"`
	RepeatCount          *int32   `protobuf:"varint,2,opt,name=repeat_count,json=repeatCount,def=1" json:"repeat_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRequest) Reset()         { *m = TestRequest{} }
func (m *TestRequest) String() string { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()    {}
func (*TestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *TestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequest.Unmarshal(m, b)
}
func (m *TestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequest.Marshal(b, m, deterministic)
}
func (m *TestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequest.Merge(m, src)
}
func (m *TestRequest) XXX_Size() int {
	return xxx_messageInfo_TestRequest.Size(m)
}
func (m *TestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequest proto.InternalMessageInfo

const Default_TestRequest_RepeatCount int32 = 1

func (m *TestRequest) GetLower() string {
	if m != nil && m.Lower != nil {
		return *m.Lower
	}
	return ""
}

func (m *TestRequest) GetRepeatCount() int32 {
	if m != nil && m.RepeatCount != nil {
		return *m.RepeatCount
	}
	return Default_TestRequest_RepeatCount
}

type TestResponse struct {
	Value                *string  `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestResponse) Reset()         { *m = TestResponse{} }
func (m *TestResponse) String() string { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()    {}
func (*TestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *TestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResponse.Unmarshal(m, b)
}
func (m *TestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResponse.Marshal(b, m, deterministic)
}
func (m *TestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResponse.Merge(m, src)
}
func (m *TestResponse) XXX_Size() int {
	return xxx_messageInfo_TestResponse.Size(m)
}
func (m *TestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestResponse proto.InternalMessageInfo

func (m *TestResponse) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type CacheStats struct {
	Items                *int64   `protobuf:"varint,1,opt,name=items" json:"items,omitempty"`
	Bytes                *int64   `protobuf:"varint,2,opt,name=bytes" json:"bytes,omitempty"`
	Gets                 *int64   `protobuf:"varint,3,opt,name=gets" json:"gets,omitempty"`
	Hits                 *int64   `protobuf:"varint,4,opt,name=hits" json:"hits,omitempty"`
	Evicts               *int64   `protobuf:"varint,5,opt,name=evicts" json:"evicts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheStats) Reset()         { *m = CacheStats{} }
func (m *CacheStats) String() string { return proto.CompactTextString(m) }
func (*CacheStats) ProtoMessage()    {}
func (*CacheStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}

func (m *CacheStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheStats.Unmarshal(m, b)
}
func (m *CacheStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheStats.Marshal(b, m, deterministic)
}
func (m *CacheStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheStats.Merge(m, src)
}
func (m *CacheStats) XXX_Size() int {
	return xxx_messageInfo_CacheStats.Size(m)
}
func (m *CacheStats) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheStats.DiscardUnknown(m)
}

var xxx_messageInfo_CacheStats proto.InternalMessageInfo

func (m *CacheStats) GetItems() int64 {
	if m != nil && m.Items != nil {
		return *m.Items
	}
	return 0
}

func (m *CacheStats) GetBytes() int64 {
	if m != nil && m.Bytes != nil {
		return *m.Bytes
	}
	return 0
}

func (m *CacheStats) GetGets() int64 {
	if m != nil && m.Gets != nil {
		return *m.Gets
	}
	return 0
}

func (m *CacheStats) GetHits() int64 {
	if m != nil && m.Hits != nil {
		return *m.Hits
	}
	return 0
}

func (m *CacheStats) GetEvicts() int64 {
	if m != nil && m.Evicts != nil {
		return *m.Evicts
	}
	return 0
}

type StatsResponse struct {
	Gets                 *int64      `protobuf:"varint,1,opt,name=gets" json:"gets,omitempty"`
	CacheHits            *int64      `protobuf:"varint,12,opt,name=cache_hits,json=cacheHits" json:"cache_hits,omitempty"`
	Fills                *int64      `protobuf:"varint,2,opt,name=fills" json:"fills,omitempty"`
	TotalAlloc           *uint64     `protobuf:"varint,3,opt,name=total_alloc,json=totalAlloc" json:"total_alloc,omitempty"`
	MainCache            *CacheStats `protobuf:"bytes,4,opt,name=main_cache,json=mainCache" json:"main_cache,omitempty"`
	HotCache             *CacheStats `protobuf:"bytes,5,opt,name=hot_cache,json=hotCache" json:"hot_cache,omitempty"`
	ServerIn             *int64      `protobuf:"varint,6,opt,name=server_in,json=serverIn" json:"server_in,omitempty"`
	Loads                *int64      `protobuf:"varint,8,opt,name=loads" json:"loads,omitempty"`
	PeerLoads            *int64      `protobuf:"varint,9,opt,name=peer_loads,json=peerLoads" json:"peer_loads,omitempty"`
	PeerErrors           *int64      `protobuf:"varint,10,opt,name=peer_errors,json=peerErrors" json:"peer_errors,omitempty"`
	LocalLoads           *int64      `protobuf:"varint,11,opt,name=local_loads,json=localLoads" json:"local_loads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StatsResponse) Reset()         { *m = StatsResponse{} }
func (m *StatsResponse) String() string { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()    {}
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{4}
}

func (m *StatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse.Unmarshal(m, b)
}
func (m *StatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse.Marshal(b, m, deterministic)
}
func (m *StatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse.Merge(m, src)
}
func (m *StatsResponse) XXX_Size() int {
	return xxx_messageInfo_StatsResponse.Size(m)
}
func (m *StatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse proto.InternalMessageInfo

func (m *StatsResponse) GetGets() int64 {
	if m != nil && m.Gets != nil {
		return *m.Gets
	}
	return 0
}

func (m *StatsResponse) GetCacheHits() int64 {
	if m != nil && m.CacheHits != nil {
		return *m.CacheHits
	}
	return 0
}

func (m *StatsResponse) GetFills() int64 {
	if m != nil && m.Fills != nil {
		return *m.Fills
	}
	return 0
}

func (m *StatsResponse) GetTotalAlloc() uint64 {
	if m != nil && m.TotalAlloc != nil {
		return *m.TotalAlloc
	}
	return 0
}

func (m *StatsResponse) GetMainCache() *CacheStats {
	if m != nil {
		return m.MainCache
	}
	return nil
}

func (m *StatsResponse) GetHotCache() *CacheStats {
	if m != nil {
		return m.HotCache
	}
	return nil
}

func (m *StatsResponse) GetServerIn() int64 {
	if m != nil && m.ServerIn != nil {
		return *m.ServerIn
	}
	return 0
}

func (m *StatsResponse) GetLoads() int64 {
	if m != nil && m.Loads != nil {
		return *m.Loads
	}
	return 0
}

func (m *StatsResponse) GetPeerLoads() int64 {
	if m != nil && m.PeerLoads != nil {
		return *m.PeerLoads
	}
	return 0
}

func (m *StatsResponse) GetPeerErrors() int64 {
	if m != nil && m.PeerErrors != nil {
		return *m.PeerErrors
	}
	return 0
}

func (m *StatsResponse) GetLocalLoads() int64 {
	if m != nil && m.LocalLoads != nil {
		return *m.LocalLoads
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{5}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TestMessage)(nil), "testpb.TestMessage")
	proto.RegisterType((*TestRequest)(nil), "testpb.TestRequest")
	proto.RegisterType((*TestResponse)(nil), "testpb.TestResponse")
	proto.RegisterType((*CacheStats)(nil), "testpb.CacheStats")
	proto.RegisterType((*StatsResponse)(nil), "testpb.StatsResponse")
	proto.RegisterType((*Empty)(nil), "testpb.Empty")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x51, 0x6b, 0x13, 0x41,
	0x10, 0xc7, 0x7b, 0x49, 0x2e, 0xe6, 0xe6, 0x52, 0x84, 0xb5, 0xca, 0x51, 0x91, 0x96, 0xa3, 0x0f,
	0x05, 0x21, 0xd2, 0x80, 0x2f, 0xbe, 0x49, 0x29, 0x31, 0xa0, 0x20, 0xa7, 0xef, 0xc7, 0xf6, 0x1c,
	0x9b, 0x85, 0xcd, 0xed, 0xb9, 0x3b, 0x89, 0xcd, 0x17, 0xf2, 0xfb, 0xf9, 0x0d, 0x64, 0x67, 0x72,
	0xb5, 0x11, 0x7c, 0x9b, 0xff, 0x6f, 0x66, 0xfe, 0xf7, 0xdf, 0xdb, 0x05, 0x20, 0x0c, 0x34, 0xeb,
	0xbc, 0x23, 0xa7, 0xc6, 0xb1, 0xee, 0x6e, 0xcb, 0xb7, 0x90, 0x7f, 0xc5, 0x40, 0x9f, 0x30, 0x04,
	0x7d, 0x87, 0x4a, 0xc1, 0xa8, 0xd5, 0x6b, 0x2c, 0x92, 0xf3, 0xe4, 0x32, 0xab, 0xb8, 0x8e, 0xac,
	0x31, 0xb4, 0x2b, 0x06, 0xc2, 0x62, 0x5d, 0x2e, 0x65, 0xad, 0xc2, 0x1f, 0x1b, 0x0c, 0xa4, 0x4e,
	0x20, 0xb5, 0xee, 0x27, 0xfa, 0x22, 0x39, 0x1f, 0x5c, 0x66, 0x95, 0x08, 0x75, 0x01, 0x53, 0x8f,
	0x1d, 0x6a, 0xaa, 0x1b, 0xb7, 0x69, 0x89, 0x0d, 0xd2, 0x77, 0xc9, 0x55, 0x95, 0x0b, 0xbe, 0x8e,
	0xb4, 0xbc, 0x80, 0xa9, 0x58, 0x85, 0xce, 0xb5, 0x01, 0xa3, 0xd7, 0x56, 0xdb, 0x4d, 0x9f, 0x41,
	0x44, 0x79, 0x0f, 0x70, 0xad, 0x9b, 0x15, 0x7e, 0x21, 0x4d, 0x21, 0xce, 0x18, 0xc2, 0x75, 0xe0,
	0x99, 0x61, 0x25, 0x22, 0xd2, 0xdb, 0x1d, 0x61, 0xe0, 0x0f, 0x0d, 0x2b, 0x11, 0x31, 0xfe, 0x1d,
	0x52, 0x28, 0x86, 0x0c, 0xb9, 0x8e, 0x6c, 0x65, 0x28, 0x14, 0x23, 0x61, 0xb1, 0x56, 0x2f, 0x60,
	0x8c, 0x5b, 0xd3, 0x50, 0x28, 0x52, 0xa6, 0x7b, 0x55, 0xfe, 0x1e, 0xc0, 0x31, 0x7f, 0xf5, 0x21,
	0x61, 0xef, 0x98, 0x3c, 0x72, 0x7c, 0x05, 0xd0, 0xc4, 0x7c, 0x35, 0xfb, 0x4e, 0xb9, 0x93, 0x31,
	0xf9, 0x60, 0x24, 0xf0, 0x77, 0x63, 0xed, 0x43, 0x34, 0x16, 0xea, 0x0c, 0x72, 0x72, 0xa4, 0x6d,
	0xad, 0xad, 0x75, 0x0d, 0x27, 0x1c, 0x55, 0xc0, 0xe8, 0x7d, 0x24, 0xea, 0x0a, 0x60, 0xad, 0x4d,
	0x5b, 0xb3, 0x11, 0xa7, 0xcd, 0xe7, 0x6a, 0x26, 0x57, 0x37, 0xfb, 0xfb, 0x3f, 0xaa, 0x2c, 0x4e,
	0xb1, 0x56, 0x6f, 0x20, 0x5b, 0x39, 0xda, 0x6f, 0xa4, 0xff, 0xdd, 0x98, 0xac, 0x1c, 0xc9, 0xc2,
	0x4b, 0xc8, 0x02, 0xfa, 0x2d, 0xfa, 0xda, 0xb4, 0xc5, 0x98, 0xe3, 0x4d, 0x04, 0x2c, 0x5b, 0xb9,
	0x58, 0xfd, 0x2d, 0x14, 0x13, 0xc9, 0xcd, 0x22, 0x1e, 0xb6, 0x43, 0xf4, 0xb5, 0xb4, 0x32, 0x39,
	0x6c, 0x24, 0x1f, 0xb9, 0x7d, 0x06, 0x39, 0xb7, 0xd1, 0x7b, 0xe7, 0x43, 0x01, 0xdc, 0xe7, 0x8d,
	0x1b, 0x26, 0x71, 0xc0, 0xba, 0x46, 0xdb, 0xbd, 0x41, 0x2e, 0x03, 0x8c, 0xd8, 0xa1, 0x7c, 0x02,
	0xe9, 0xcd, 0xba, 0xa3, 0xdd, 0xfc, 0x57, 0x02, 0x4f, 0x17, 0xda, 0xea, 0xfb, 0x1d, 0x87, 0x8d,
	0x0f, 0x45, 0xbd, 0x86, 0x6c, 0xd9, 0x1a, 0xfa, 0x8c, 0xe8, 0x83, 0x3a, 0xee, 0xcf, 0xc6, 0xf3,
	0xa7, 0x87, 0xb2, 0x3c, 0x52, 0x73, 0x18, 0x2e, 0x90, 0xd4, 0xb3, 0x9e, 0x3f, 0x7a, 0xb5, 0xa7,
	0x27, 0x87, 0x50, 0x6e, 0x97, 0x77, 0x26, 0x0b, 0x24, 0x79, 0x69, 0xff, 0xf8, 0x3f, 0xef, 0xe5,
	0xc1, 0x8b, 0x28, 0x8f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x51, 0x7f, 0xd4, 0x9e, 0x5c, 0x03,
	0x00, 0x00,
}
