// Code generated by protoc-gen-go. DO NOT EDIT.
// source: galaxycache.proto

package galaxycachepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	Galaxy               string   `protobuf:"bytes,1,opt,name=galaxy,proto3" json:"galaxy,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23bd509ca7b74957, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetGalaxy() string {
	if m != nil {
		return m.Galaxy
	}
	return ""
}

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	MinuteQps            float64  `protobuf:"fixed64,2,opt,name=minute_qps,json=minuteQps,proto3" json:"minute_qps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23bd509ca7b74957, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetResponse) GetMinuteQps() float64 {
	if m != nil {
		return m.MinuteQps
	}
	return 0
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "galaxycachepb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "galaxycachepb.GetResponse")
}

func init() { proto.RegisterFile("galaxycache.proto", fileDescriptor_23bd509ca7b74957) }

var fileDescriptor_23bd509ca7b74957 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x4f, 0xcc, 0x49,
	0xac, 0xa8, 0x4c, 0x4e, 0x4c, 0xce, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x45,
	0x12, 0x2a, 0x48, 0x52, 0x32, 0xe3, 0xe2, 0x72, 0x4f, 0x2d, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x11, 0x12, 0xe3, 0x62, 0x83, 0x48, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79,
	0x42, 0x02, 0x5c, 0xcc, 0xd9, 0xa9, 0x95, 0x12, 0x4c, 0x60, 0x41, 0x10, 0x53, 0xc9, 0x89, 0x8b,
	0x1b, 0xac, 0xaf, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7,
	0x34, 0x15, 0xac, 0x8f, 0x27, 0x08, 0xc2, 0x11, 0x92, 0xe5, 0xe2, 0xca, 0xcd, 0xcc, 0x2b, 0x2d,
	0x49, 0x8d, 0x2f, 0x2c, 0x28, 0x06, 0xeb, 0x66, 0x0c, 0xe2, 0x84, 0x88, 0x04, 0x16, 0x14, 0x1b,
	0x85, 0x73, 0x71, 0xbb, 0x23, 0x1c, 0x23, 0xe4, 0xc1, 0xc5, 0xeb, 0x9e, 0x5a, 0xe2, 0x56, 0x94,
	0x9f, 0x1b, 0x94, 0x9a, 0x9b, 0x5f, 0x92, 0x2a, 0x24, 0xa9, 0x87, 0xe2, 0x56, 0x3d, 0x84, 0x43,
	0xa5, 0xa4, 0xb0, 0x49, 0x41, 0xdc, 0xa2, 0xc4, 0x90, 0xc4, 0x06, 0xf6, 0xaa, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x6c, 0x17, 0xf8, 0xc6, 0xff, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GalaxycacheClient is the client API for Galaxycache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GalaxycacheClient interface {
	GetFromRemote(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type galaxycacheClient struct {
	cc *grpc.ClientConn
}

func NewGalaxycacheClient(cc *grpc.ClientConn) GalaxycacheClient {
	return &galaxycacheClient{cc}
}

func (c *galaxycacheClient) GetFromRemote(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/galaxycachepb.Galaxycache/GetFromRemote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GalaxycacheServer is the server API for Galaxycache service.
type GalaxycacheServer interface {
	GetFromRemote(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterGalaxycacheServer(s *grpc.Server, srv GalaxycacheServer) {
	s.RegisterService(&_Galaxycache_serviceDesc, srv)
}

func _Galaxycache_GetFromRemote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalaxycacheServer).GetFromRemote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/galaxycachepb.Galaxycache/GetFromRemote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalaxycacheServer).GetFromRemote(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Galaxycache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "galaxycachepb.Galaxycache",
	HandlerType: (*GalaxycacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFromRemote",
			Handler:    _Galaxycache_GetFromRemote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "galaxycache.proto",
}
