//
//Copyright 2012 Google Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: galaxycachepb/galaxycache.proto

package galaxycachepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GalaxyCache_GetFromPeer_FullMethodName = "/galaxycachepb.GalaxyCache/GetFromPeer"
)

// GalaxyCacheClient is the client API for GalaxyCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GalaxyCacheClient interface {
	GetFromPeer(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type galaxyCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewGalaxyCacheClient(cc grpc.ClientConnInterface) GalaxyCacheClient {
	return &galaxyCacheClient{cc}
}

func (c *galaxyCacheClient) GetFromPeer(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, GalaxyCache_GetFromPeer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GalaxyCacheServer is the server API for GalaxyCache service.
// All implementations must embed UnimplementedGalaxyCacheServer
// for forward compatibility
type GalaxyCacheServer interface {
	GetFromPeer(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedGalaxyCacheServer()
}

// UnimplementedGalaxyCacheServer must be embedded to have forward compatible implementations.
type UnimplementedGalaxyCacheServer struct {
}

func (UnimplementedGalaxyCacheServer) GetFromPeer(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFromPeer not implemented")
}
func (UnimplementedGalaxyCacheServer) mustEmbedUnimplementedGalaxyCacheServer() {}

// UnsafeGalaxyCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GalaxyCacheServer will
// result in compilation errors.
type UnsafeGalaxyCacheServer interface {
	mustEmbedUnimplementedGalaxyCacheServer()
}

func RegisterGalaxyCacheServer(s grpc.ServiceRegistrar, srv GalaxyCacheServer) {
	s.RegisterService(&GalaxyCache_ServiceDesc, srv)
}

func _GalaxyCache_GetFromPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalaxyCacheServer).GetFromPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalaxyCache_GetFromPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalaxyCacheServer).GetFromPeer(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GalaxyCache_ServiceDesc is the grpc.ServiceDesc for GalaxyCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GalaxyCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "galaxycachepb.GalaxyCache",
	HandlerType: (*GalaxyCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFromPeer",
			Handler:    _GalaxyCache_GetFromPeer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "galaxycachepb/galaxycache.proto",
}
